name       : python-testpath
version    : 0.4.3
release    : 3
source     :
    - https://files.pythonhosted.org/packages/4b/bc/8f6b08004266976235b53510aa9833a19b65ee8ebc251e699a8ba067ee0f/testpath-0.4.3.tar.gz : a15a90476b3b0eae847b132431567942b439a349da2769dd54774c34fb9cf7b4
license    : BSD-3-Clause
component  : programming.python
summary    : Test utilities for Python code working with files and commands.
description: |
    Test utilities for Python code working with files and commands.
builddeps  :
    - pkgconfig(python3)
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
