name       : python-testpath
version    : 0.5.0
release    : 8
source     :
    - https://pypi.io/packages/source/t/testpath/testpath-0.5.0.tar.gz : 1acf7a0bcd3004ae8357409fc33751e16d37ccc650921da1094a86581ad1e417
homepage   : https://pypi.org/project/testpath
license    : BSD-3-Clause
component  : programming.python
summary    : Test utilities for Python code working with files and commands
description: |
    Test utilities for Python code working with files and commands. It contains functions to check things on the filesystem, and tools for mocking system commands and recording calls to those.
builddeps  :
    - python-pytest
setup      : |
    %python3_setup
install    : |
    %python3_install

    # Remove windows stuff
    rm -f $installdir/usr/lib/python%python3_version%/site-packages/testpath/{cli-32.exe,cli-64.exe}
check      : |
    %python3_test pytest3
