name       : python-testpath
version    : 0.4.4
release    : 6
source     :
    - https://files.pythonhosted.org/packages/2c/b3/5d57205e896d8998d77ad12aa42ebce75cd97d8b9a97d00ba078c4c9ffeb/testpath-0.4.4.tar.gz : 60e0a3261c149755f4399a1fff7d37523179a70fdc3abdf78de9fc2604aeec7e
homepage   : https://pypi.org/project/testpath
license    : BSD-3-Clause
component  : programming.python
summary    : Test utilities for Python code working with files and commands
description: |
    Test utilities for Python code working with files and commands. It contains functions to check things on the filesystem, and tools for mocking system commands and recording calls to those.
builddeps  :
    - python-pytest
setup      : |
    %python3_setup
install    : |
    %python3_install
    
    # Remove windows stuff
    rm -f $installdir/usr/lib/python3.7/site-packages/testpath/{cli-32.exe,cli-64.exe}
check      : |
    %python3_test pytest3
