name       : python-testpath
version    : 0.3.1
release    : 1
source     :
    - https://pypi.python.org/packages/f4/8b/b71e9ee10e5f751e9d959bc750ab122ba04187f5aa52aabdc4e63b0e31a7/testpath-0.3.1.tar.gz : 0d5337839c788da5900df70f8e01015aec141aa3fe7936cb0d0a2953f7ac7609
license    : MIT
component  : programming.python
summary    : Test utilities for Python code working with files and commands.
description: |
    Test utilities for Python code working with files and commands.
builddeps  :
    - pkgconfig(python-3.5)
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
